title: Luxury Desert Mountain Rental
email: support@zebradog.com
description:
baseurl: "/luxurydesertmountainrental.com"
url: "https://www.luxurydesertmountainrental.com"
markdown: kramdown
sass:
  style: compressed
